name: Deploy Frontend
on:
  push:
    branches: [ "main" ]
    paths:
      - 'frontend/**'  # Only run when frontend code changes
      - '.github/workflows/deploy-frontend.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    needs: deploy-infrastructure  # Wait for infrastructure to be ready
    permissions:
      contents: read
      id-token: write

    env:
      AWS_REGION: "eu-north-1"

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install and Build
        run: |
          cd frontend
          npm ci  # Clean install
          npm run build

      - name: Deploy to S3
        run: |
          aws s3 sync ./frontend/dist s3://${{ needs.deploy-infrastructure.outputs.s3_bucket }} \
            --delete \
            --cache-control "public, max-age=31536000, immutable"  # Cache static assets

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ needs.deploy-infrastructure.outputs.cloudfront_distribution_id }} \
            --paths "/*"
